Add errors for Only H1 headings
ploomber/soorgeon pull request #60
Opened 2022-06-06 20:42 UTC by 94rain

## Describe your changes
* Add errors for Only H1 headings:
  * Logic:
      * No H2 headers:
          * Only H1 headers: `Only H1 headings are found. At this time, only H2 heading are supported.`
          * No H1 and H2 headers: `Expected notebook to have at least one markdown H2 heading.`
      * Only one H2 header: Warning: `refactoring successful but only one H2 heading detected...`
      * Otherwise: run smoothly
* Add a new test case for `_get_h2_header` (`###`->None), and a new method `_get_h1_header` along with tests
* Update test `test_find_breaks_error_if_no_h2_headers` to `test_find_breaks_error_if_no_h2_but_h1_headers` and `test_find_breaks_error_if_no_h1_and_h2_headers`

## Issue ticket number and link
Closes #5 

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have added thorough tests (when necessary).
- [x] I have added the right documentation (when needed). Product update? If yes, write one line about this update.
 - Update: Fixed the issue of matching H3 or smaller headers as H2. Add error messages when there are only H1 headers.

2022-06-06 21:45 UTC, edublancas requested changes

2022-06-06 21:45 UTC, edublancas commented on src/soorgeon/split.py
> +def _get_h1_header(md):
given that `_get_h1_header` and `_get_h2_header`, we can create a "factory" that generates both, something like this:

```
def _get_header_factory(regex):
    def _get_header(md):
         # put the body of the function here, and pass regex to re.search
    
    return _get_header


_get_h1_header  = _get_header_factory(regex_for_h1)
_get_h2_header  = _get_header_factory(regex_for_h2)
```

2022-06-06 21:45 UTC, edublancas commented
looks good, only a small change

2022-06-07 16:08 UTC, 94rain commented
> looks good, only a small change

Done. Please take another look.

2022-06-07 18:29 UTC, idomic commented
lgtm, nice job!

2022-06-07 18:29 UTC, merged