refactored code, down load from github instead of kaggle
ploomber/soorgeon pull request #64
Opened 2022-06-14 14:57 UTC by Wxl19980214

## Describe your changes
1. Instead of fetching from kaggle, we fetch from github by pygithub api now
2. Add _pygithub.py for downloading a dir from a repo.
3. Add pygithub package to setup.py (I don't know if this one is necessary)
5. Removed stored notebooks under _kaggle since we can store them in the storage repo now
6. Removed unused functions under src/_kaggle.py
7. Removed kaggle username and key in CI, I don't think we need them. Maybe we can also remove them from repo secrets
8.  Storage repo [here](https://github.com/ploomber/ci-notebooks) and README.md has instructions on how to upload
9. Contribute.md remains unchanged, we can let user register new notebook in _kaggle/index.yaml. But the rest of downloading and uploading, updating CI and test cases will need to be done manually by one of the team members.

## To do
1.We need to add a personal access token to the repo's secrets.
2. Right now CI will fail because this one fails test_notebooks[look-at-this-note-feature-engineering-is-easy] for this reason:
E               soorgeon.exceptions.InputError: Only H1 headings are found. At this time, only H2 headings are supported. Check out our guide: 
## Issue ticket number and link
Closes #59 

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have added thorough tests (when necessary).
- [x] I have added the right documentation (when needed). Product update? If yes, write one line about this update.

2022-06-14 18:55 UTC, Wxl19980214 commented
@edublancas  Yeah it is. I put it in the To Do list. We need a PAT in repo's secrets. Also one of the test case is failing anyway

2022-06-17 10:13 UTC, edublancas commented
ok so most of them pass now. but there's one that still fails `look-at-this-note-feature-engineering-is-easy`. did anything change from the file we had here to the one that's being downloaded? looks like it has H1 headings now

2022-06-17 11:42 UTC, idomic commented
Yeah we're on it, we introduced a feature to reject H1s, we'll change it to H2s in the notebook and that should fix it.

2022-06-17 13:06 UTC, Wxl19980214 commented
Just updated notebooks. The last check should pass. But still, I do think we need to put a token in to make sure it does't fail in the future. I think there's a limitation on api request for non-login request. I am asking shuyang to generate a pat to test if it works. I don't even know why it works without authentication, but it mostly because our repo is public.

2022-06-17 13:19 UTC, idomic commented
lmk and I'll remove the PAT. Yeah I think it's because it's a public repo.

2022-06-17 16:49 UTC, idomic commented on .github/workflows/ci.yaml
> +          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN}}
Can we remove this if we're no longer using this secret?

2022-06-17 16:50 UTC, idomic commented on src/soorgeon/_pygithub.py
> +    # token = os.getenv("PERSONAL_ACCESS_TOKEN")
Same here, remove if not used.

2022-06-17 16:50 UTC, idomic requested changes
Added small comments

2022-06-17 16:59 UTC, Wxl19980214 commented
@idomic I left them there on purpose just in case we encounter some errors later. But I can remove it for now. It's easy fix anyway

2022-06-17 17:43 UTC, merged